### PR TITLE
Closes #20 Allow developer to set a custom :message to override the status code mapped value

### LINKED ISSUE #20: Allow custom friendly message over top of the status_code -> message map
Right now the only way to get a friendly message is to use the status code as the map key. Sometimes an exception itself might call for a more refined message. Please add a `:message` option to the registration method that will take priority over the mapped status_code value.

### PR DESCRIPTION
**Pull request by joemsak**
I'm not entirely pleased with this code... something feels tangled about it. Could use some help sniffing out the code smells...

### CODE REVIEW

File: lib/openstax/rescue_from.rb [hunk 1]
```diff
@@ -44,8 +47,10 @@ def notifying_exceptions
         @@registered_exceptions.select { |_, v| v.notify? }.keys
       end
 
-      def friendly_message(status)
-        friendly_status_messages[status] || default_friendly_message
+      def friendly_message(exception)
+        friendly_status_messages[exception.name] ||
+          friendly_status_messages[exception.status] ||
+            default_friendly_message
```
Comment (jpslav) [inline lib/openstax/rescue_from.rb]: Think this should be

```ruby
      def friendly_message(exception)
        @@registered_exceptions[exception.name].message ||
        friendly_status_messages[exception.status] ||
        default_friendly_message
      end
```

and remove line 21 and 23 above
